---
# x-Nord OS Users module
allowWeakPasswords: false
userGroup: users
defaultGroups:
    - sudo
    - audio
    - video
    - network
    - storage
    - optical
    - power
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
