# x-Nord OS Calamares configuration
# 5-step installer: Welcome -> Partition -> Users -> Summary -> Install

modules-search:
    - local

branding: xnord

sequence:
    - show:
        - welcome
        - locale
        - keyboard
        - partition
        - users
        - summary
    - exec:
        - partition
        - mount
        - unpackfs
        - machineid
        - locale
        - keyboard
        - localecfg
        - fstab
        - initramfs
        - users
        - displaymanager
        - networkcfg
        - hwclock
        - services-systemd
        - initramfs
        - bootloader
        - umount
    - show:
        - finished

prompt-install: false
dont-chroot: false
